CREATE OR REPLACE FUNCTION add_comando_sincronizar_matriz() RETURNS TRIGGER AS
$$
DECLARE
	idFl integer;
BEGIN
	FOR idFl in
		SELECT ID FROM FILIAL
	LOOP
		IF idFl <> 1 THEN
			IF TG_OP <> 'DELETE' THEN		    
				INSERT INTO SINCRONIZAR (IDFILIAL, IDFILIAL_PK, IDOPERACAO, TIPO_OPERACAO, TABELA, ITEM) VALUES (idFl, 1, NEW.ID, TG_OP, TG_RELNAME, 0);		    
			ELSE
				INSERT INTO SINCRONIZAR (IDFILIAL, IDFILIAL_PK, IDOPERACAO, TIPO_OPERACAO, TABELA, ITEM) VALUES (idFl, 1, OLD.ID, TG_OP, TG_RELNAME, 0);		    
			END IF;
		END IF;
	END LOOP; 
	RETURN NEW;      
END;
$$ LANGUAGE 'plpgsql';