CREATE TABLE CAIXA (
    ID           INTEGER NOT NULL,
    DT_INC       DATE,
    NUM_CAIXA    INTEGER NOT NULL,
    CONTROLE     INTEGER NOT NULL,
    IDFILIAL     INTEGER NOT NULL,

    CONSTRAINT PK_CAIXA PRIMARY KEY (ID, IDFILIAL),
    CONSTRAINT FK_CAIXA_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (ID)
);

CREATE TRIGGER caixa_cmd_tg
  AFTER INSERT OR UPDATE OR DELETE
  ON caixa
  FOR EACH ROW
  EXECUTE PROCEDURE add_comando_sincronizar();
