CREATE TABLE CNT_RECEBER_CHEQUE (
    ID              integer,
    IDFILIAL        integer NOT NULL,
    IDRECEBER_ITEM  integer,
    IDBANCO         integer,
    AGENCIA         CHARACTER VARYING(10),
    CONTA           CHARACTER VARYING(10),
    NUM_CHEQUE      CHARACTER VARYING(10),
    DT_EMISSAO      DATE,
    EMITENTE        CHARACTER VARYING(150),
    VALOR           NUMERIC(17,4),
    DT_VENCIMENTO   DATE,
    CONSTRAINT PK_CHEQUE PRIMARY KEY (ID, IDFILIAL),
    CONSTRAINT FK_CHEQUE_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL,
    CONSTRAINT FK_CHEQUE_RECEBER_ITEM FOREIGN KEY (IDRECEBER_ITEM, IDFILIAL) REFERENCES CNT_RECEBER_ITEM,
    CONSTRAINT FK_CHEQUE_BANCO FOREIGN KEY (IDBANCO) REFERENCES BANCO (ID)
);