CREATE TABLE CNT_RECEBER_ITEM (
    ID           INTEGER,
    IDFILIAL     INTEGER NOT NULL,
    POSICAO      CHARACTER(2),
    PREFIXO      CHARACTER(2),
    REFERENCIA   CHARACTER(12),
    IDRECEBER    INTEGER,
    DT_VENC      DATE,
    DT_PAG       DATE,
    ACRESCIMO    NUMERIC(17,4),
    DESCONTO     NUMERIC(17,4),
    VALOR        NUMERIC(17,4),
    VALOR_PAGO   NUMERIC(17,4),
    HISTORICO    CHARACTER VARYING(200),
    PARCELA      CHARACTER(6),
    CONSTRAINT PK_RECEBER_ITEM PRIMARY KEY (ID, IDFILIAL),
    CONSTRAINT FK_RECEBER_ITEM_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL,
    CONSTRAINT FK_RECEBER_ITEM_RECEBER FOREIGN KEY (IDRECEBER, IDFILIAL) REFERENCES CNT_RECEBER
);