CREATE TABLE COR_GRUPO (
    IDCOR        INTEGER,
    IDGRUPO      INTEGER,
    DT_INC       DATE,
    DT_ALT       DATE,
    STATUS       CHARACTER(1),
    CONSTRAINT PK_COR_GRUPO PRIMARY KEY (IDCOR, IDGRUPO),
    CONSTRAINT FK_COR_GRUPO_GRUPO FOREIGN KEY (IDGRUPO) REFERENCES GRUPO (ID),
    CONSTRAINT FK_COR_GRUPO_COR FOREIGN KEY (IDCOR) REFERENCES COR (ID)
);