CREATE TABLE PEDIDO (
    ID              INTEGER,
    IDFILIAL        INTEGER,
    DT_INC          DATE,
    STATUS          CHARACTER(2),
    IDCLIENTE       INTEGER,
    IDVENDEDOR      INTEGER,
    IDFORMA_PAG     INTEGER,
    VLR_TOTITEM     NUMERIC(17,4),
    VLR_DESCONTO    NUMERIC(17,4),
    VLR_FRETE       NUMERIC(17,4),
    VLR_TOTAL       NUMERIC(17,4),
    PESO            NUMERIC(17,4),
    PREFIXO         CHARACTER(2),
    DT_ALT          DATE,
    DT_CONFIRMACAO  DATE,
    DT_FECHAMENTO   DATE,
    SUBTRIBUTARIA   NUMERIC(17,4),

    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID, IDFILIAL),
    CONSTRAINT FK_PEDIDO_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (ID),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (ID),
    CONSTRAINT FK_PEDIDO_FORMA_PAG FOREIGN KEY (IDFORMA_PAG) REFERENCES FORMA_PAGAMENTO (ID),
    CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY (IDVENDEDOR) REFERENCES VENDEDOR (ID)
    

    );

    