CREATE TABLE ROMANEIO (
    ID               INTEGER,
    IDFILIAL         INTEGER,
    DT_INC           DATE,
    DT_ALT           DATE,
    STATUS           CHARACTER(2),
    PESO_TOTAL       NUMERIC(17,4),
    IDROTA           INTEGER,
    IDMOTORISTA      INTEGER,
    IDVEICULO        INTEGER,
    KM_MAXIMA        NUMERIC(17,4),
    DT_TRANSPORTE    DATE,
    DT_CONF_ENTREGA  DATE,

    CONSTRAINT PK_ROMANEIO PRIMARY KEY(ID, IDFILIAL),
    CONSTRAINT FK_ROMANEIO_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (ID),
    CONSTRAINT FK_ROMANEIO_ROTA FOREIGN KEY (IDROTA) REFERENCES ROTA (ID),
    CONSTRAINT FK_ROMANEIO_MOTORISTA FOREIGN KEY (IDMOTORISTA, IDFILIAL) REFERENCES MOTORISTA,
    CONSTRAINT FK_ROMANEIO_VEICULO FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (ID)
);