CREATE TABLE SINCRONIZAR (

	ID SERIAL,
	IDFILIAL INTEGER NOT NULL,
	IDOPERACAO INTEGER NOT NULL,
	TIPO_OPERACAO CHAR(1),
	TABELA CHARACTER VARYING(30),
	PRIMARY KEY (ID),
	CONSTRAINT FK_SINCRONIZAR_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL

)