CREATE TABLE TAMANHO (
    ID              INTEGER,
    DT_INC          DATE,
    DT_ALT          DATE,
    STATUS          CHARACTER(1),
    NOME            CHARACTER VARYING(250),
    REFERENCIA      CHARACTER VARYING(4),
    ALTURA_I        NUMERIC(17,4),
    LARGURA_I       NUMERIC(17,4),
    PROFUNDIDADE_I  NUMERIC(17,4),
    ALTURA_E        NUMERIC(17,4),
    LARGURA_E       NUMERIC(17,4),
    PROFUNDIDADE_E  NUMERIC(17,4),
    CONSTRAINT PK_TAMANHO PRIMARY KEY (ID) 
);