CREATE TABLE VENDA_ITEM (
    IDVENDA         INTEGER NOT NULL,
    ITEM            INTEGER NOT NULL,
    IDPROD_ITEM     INTEGER NOT NULL,
    DT_INC          DATE,
    QTN             NUMERIC(17,4),
    VLR_UNITARIO    NUMERIC(17,4),
    VLR_DESCONTO    NUMERIC(17,4),
    VLR_TOTAL       NUMERIC(17,4),
    PESO            NUMERIC(17,4),
    QTN_RETORNO     INTEGER,
    MOTIVO_RETORNO  CHARACTER VARYING(200),
    IDFILIAL        INTEGER NOT NULL,

    CONSTRAINT PK_VENDAITEM PRIMARY KEY (IDVENDA, ITEM, IDFILIAL),
    CONSTRAINT FK_VENDAITEM_PROD_ITEM FOREIGN KEY (IDPROD_ITEM) REFERENCES PRODUTO_ITEM (ID),
    CONSTRAINT FK_VENDAITEM_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (ID),
    CONSTRAINT FK_VENDAITEM_VENDA FOREIGN KEY (IDVENDA, IDFILIAL) REFERENCES VENDA (ID, IDFILIAL)
);