delete from contas_descricao;
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (1, '2016-06-03', 'Vendas à Vista', 'E');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (3, '2016-06-03', 'Vendas a Prazo (NT)', 'E');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (4, '2016-06-03', 'Vendas a Prazo (CH)', 'E');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (5, '2016-06-03', 'Outras Entradas', 'E');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (6, '2016-06-03', 'Fornecedores à Vista', 'S');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (7, '2016-06-03', 'Fornecedores a Prazo', 'S');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (8, '2016-06-03', 'Comissão de Vendedores', 'S');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (9, '2016-06-03', 'Outras Saídas', 'S');
INSERT INTO CONTAS_DESCRICAO (ID, DT_INC, DESCRICAO, TIPO) VALUES (2, '2016-06-04', 'Vendas Cartão Crédito', 'E');

COMMIT WORK;
