INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (1, '2014-08-18', NULL, 'Dinheiro', 0, 'DN', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (5, '2015-08-27', NULL, 'Financeira', 12, 'FN', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (6, '2015-08-27', NULL, 'Duplicata', 12, 'NT', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (7, '2015-08-28', NULL, 'Vale Desconto', 0, 'VD', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (8, '2015-08-28', NULL, 'Ticket', 0, 'TK', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (2, '2015-08-18', NULL, 'Cartão de Crédito', 12, 'CT', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (3, '2015-08-18', NULL, 'Cartão de Débito', 0, 'CD', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (4, '2015-08-18', NULL, 'Cheque', 12, 'CH', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (0, '2015-08-18', NULL, 'Recebimento Agrupado', 12, 'RA', 'N');
INSERT INTO FORMA_PAGAMENTO (ID, DT_INC, DT_ALT, NOME, PARCELA_MAXIMA, MOEDA, ENVIADO_WEB) VALUES (9, '2016-01-11', NULL, 'Crédito', 0, 'CR', 'N');

COMMIT WORK;
