INSERT INTO TAMANHO (ID, DT_INC, DT_ALT, STATUS, NOME, REFERENCIA, ALTURA_I, LARGURA_I, PROFUNDIDADE_I, ALTURA_E, LARGURA_E, PROFUNDIDADE_E, ENVIADO_WEB) VALUES (0, '2015-02-25', NULL, 'A', 'GERAL', 'TG', 0, 0, 0, 0, 0, 0, 'S');

COMMIT WORK;
