ALTER TRIGGER VENDA_ITEM_MOVIMENTACAO INACTIVE;
COMMIT WORK;
INSERT INTO VENDA_ITEM (IDVENDA, ITEM, IDPROD_ITEM, DT_INC, QTN, VLR_UNITARIO, VLR_DESC_ACRE, VLR_TOTAL, PESO, QTN_RETORNO, MOTIVO_RETORNO, ENVIADO_WEB, IDFILIAL, ENTREGAR, TIPO_DESC_ACRE, TIPO_RETORNO)
VALUES (0, 1, 1, CURRENT_DATE, 0, 0, 0, 0, 0, 0, NULL, 'N', 1, 'N', NULL, NULL);
COMMIT WORK;
ALTER TRIGGER VENDA_ITEM_MOVIMENTACAO ACTIVE;
COMMIT WORK;
