INSERT INTO VENDEDOR (STATUS, NOME, DT_NASC, TELEFONE, ENDERECO, BAIRRO, IDCIDADE, CEP, RG, CPF, SEXO, EMAIL, CELULAR, ENVIADO_WEB, IDFILIAL) VALUES ('A', 'VENDEDOR GERAL', NULL, '1', 'RUA', 'S', 448, '2', NULL, NULL, 'M', NULL, '9', 'S', 1);
COMMIT WORK;
