INSERT INTO CLIENTE (ID, DT_ALT, STATUS, NOME, DT_NASC, TELEFONE, ENDERECO, BAIRRO, IDCIDADE, CEP, RG, CPF, SEXO, PROFISSAO, EMAIL, CELULAR, TIPO, RAZAOSOCIAL, CONTATO, CNPJ, IE, IDVENDEDOR, EMAIL_NFE, KM_TOTAL, DT_ULTIMO_CONTATO, LIMITE_CREDITO, IDFORMA_PAGAMENTO, IDROTA, ENVIADO_WEB, IDFILIAL) VALUES (99999, NULL, 'A', 'CLIENTE VENDA A VISTA', '2014-12-12', '1            ', 'R', '1', 1, '28300000', '1              ', '               ', 'M', '', 'M', '1            ', 'F', '', '', '', '', 1, '', NULL, NULL, 0, 1, 1, 'S', 1);

COMMIT WORK;
