INSERT INTO FILIAL (STATUS, NOME, ENDERECO, BAIRRO, IDCIDADE, CEP, TELEFONE1, TELEFONE2, EMAIL, IDROTA, ENVIADO_WEB) VALUES ('A', 'LOJA', 'RUA', 'I', 430, '2', '2', '2', 'FINANCEIRO', 1, 'S');

COMMIT WORK;
