CREATE OR REPLACE FUNCTION add_comando_sincronizar() RETURNS TRIGGER AS
$$
DECLARE
	idFilial integer;
BEGIN
	FOR idFilial in
		SELECT ID FROM FILIAL
	LOOP
		IF TG_OP <> 'DELETE' THEN
		    IF (idFilial <> NEW.IDFILIAL) THEN		    
			INSERT INTO SINCRONIZAR (IDFILIAL, IDFILIAL_PK, IDOPERACAO, TIPO_OPERACAO, TABELA, ITEM) VALUES (idFilial, NEW.IDFILIAL, NEW.ID, TG_OP, TG_RELNAME, 0);		    
		    END IF;
		ELSE
	            IF (idFilial <> OLD.IDFILIAL) THEN		    
			INSERT INTO SINCRONIZAR (IDFILIAL, IDFILIAL_PK, IDOPERACAO, TIPO_OPERACAO, TABELA, ITEM) VALUES (idFilial, OLD.IDFILIAL, NEW.ID, TG_OP, TG_RELNAME, 0);		    
		    END IF;
	        END IF;
	END LOOP; 
	RETURN NEW;      
END;
$$ LANGUAGE 'plpgsql';