CREATE OR REPLACE FUNCTION add_comando_sincronizar() RETURNS TRIGGER AS
$$
DECLARE
	idFl integer;
BEGIN
	FOR idFl in
		SELECT ID FROM FILIAL
	LOOP
		IF TG_OP <> 'DELETE' THEN		    
			INSERT INTO SINCRONIZAR (IDFILIAL, IDFILIAL_PK, IDOPERACAO, TIPO_OPERACAO, TABELA, ITEM) VALUES (idFl, NEW.IDFILIAL, NEW.ID, TG_OP, TG_RELNAME, 0);		    
		ELSE		    
			INSERT INTO SINCRONIZAR (IDFILIAL, IDFILIAL_PK, IDOPERACAO, TIPO_OPERACAO, TABELA, ITEM) VALUES (idFl, OLD.IDFILIAL, OLD.ID, TG_OP, TG_RELNAME, 0);		    
	        END IF;
	END LOOP; 
	RETURN NEW;      
END;
$$ LANGUAGE 'plpgsql';