CREATE TABLE BANCO (
    ID         INTEGER,
    DT_INC     DATE,
    DT_ALT     DATE,
    STATUS     CHARACTER(1),
    DESCRICAO  CHARACTER VARYING(150),
    NUM_BANCO  CHARACTER(3),
    CONSTRAINT PK_BANCO PRIMARY KEY (ID)
);