CREATE TABLE COR (
    ID           INTEGER,
    DT_INC       DATE,
    DT_ALT       DATE,
    STATUS       CHARACTER(1),
    NOME         CHARACTER VARYING(250),
    REFERENCIA   CHARACTER VARYING(4),
    CONSTRAINT PK_COR PRIMARY KEY (ID)
);
