CREATE TABLE MOTORISTA (
    ID           INTEGER,
    IDFILIAL 	 INTEGER NOT NULL,
    DT_INC       DATE,
    DT_ALT       DATE,
    STATUS       CHARACTER(1),
    NOME         CHARACTER VARYING(250),
    NCNH         CHARACTER VARYING(20),
    TIPOCNH      CHARACTER VARYING(2),

    CONSTRAINT PK_MOTORISTA PRIMARY KEY (ID, IDFILIAL),
    CONSTRAINT FK_MOTORISTA_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL
);