CREATE TABLE MOVIMENTACAO_ITEM (
    ID                INTEGER NOT NULL,
    DT_INC            DATE,
    IDITEM            INTEGER,
    IDFILIAL          INTEGER,
    MOVIMENTO         CHARACTER VARYING(30),
    IDMOVIMENTO       INTEGER,
    TIPO              CHARACTER(1),
    QTN               NUMERIC(15,3),
    SALDO             NUMERIC(15,3),
    IDFILIAL_DESTINO  INTEGER NOT NULL,

    CONSTRAINT PK_MOVITEM PRIMARY KEY (ID, IDFILIAL),
    CONSTRAINT FK_MOV_ITEM_FILIAL FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (ID),
    CONSTRAINT FK_MOV_ITEM_FILIAL2 FOREIGN KEY (IDFILIAL_DESTINO) REFERENCES FILIAL (ID),
    CONSTRAINT FK_MOV_ITEM_ITEM FOREIGN KEY (IDITEM) REFERENCES PRODUTO_ITEM (ID)
)