CREATE TABLE PRODUTO (
    ID                  INTEGER,
    DT_INC              DATE,
    DT_ALT              DATE,
    STATUS              CHARACTER(1),
    NOME                CHARACTER VARYING(250),
    REFERENCIA          CHARACTER VARYING(4),
    IDGRUPO             INTEGER,
    IDFORNECEDOR        INTEGER,
    FABRICACAO_PRORPIA  CHARACTER(1),
    DESCRICAO           TEXT,

    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUTO_GRUPO FOREIGN KEY (IDGRUPO) REFERENCES GRUPO (ID),
    CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR (ID)
);