CREATE TABLE TAMANHO_GRUPO (
    IDTAMANHO    INTEGER,
    IDGRUPO      INTEGER,
    DT_INC       DATE,
    DT_ALT       DATE,
    STATUS       CHARACTER(1),
    
    CONSTRAINT PK_TAMANHO_GRUPO PRIMARY KEY (IDTAMANHO, IDGRUPO),
    CONSTRAINT FK_TAMNHO_GRUPO_GRUPO FOREIGN KEY (IDGRUPO) REFERENCES GRUPO (ID),
    CONSTRAINT FK_TAMANHO_GRUPO_TAMANHO FOREIGN KEY (IDTAMANHO) REFERENCES TAMANHO (ID)
);