program SGP;

uses
  Forms,
  untPrincipal in 'untPrincipal.pas' {frmPrincipal},
  untCadClientes in 'untCadClientes.pas' {frmCadClientes},
  untData in 'untData.pas' {DM: TDataModule},
  untCadUsuarios in 'untCadUsuarios.pas' {frmCadUsuarios},
  untLogin in 'untLogin.pas' {frmLogin},
  untPesqCidade in 'untPesqCidade.pas' {frmPesqCidade},
  untCadVendedores in 'untCadVendedores.pas' {frmCadVendedores},
  untCadGrupos in 'untCadGrupos.pas' {frmCadGrupos},
  untCadTamanhos in 'untCadTamanhos.pas' {frmCadTamanhos},
  untCadCores in 'untCadCores.pas' {frmCadCores},
  untCaProdutos in 'untCaProdutos.pas' {frmCadProdutos},
  untCadFornecedor in 'untCadFornecedor.pas' {frmCadFornecedor},
  untPesqFornecedor in 'untPesqFornecedor.pas' {frmPesqFornecedor},
  untCadFormasPagamento in 'untCadFormasPagamento.pas' {frmCadFormasPagamento},
  untPedidos in 'untPedidos.pas' {frmPedidos},
  untPesqGrupo in 'untPesqGrupo.pas' {frmPesqGrupo},
  untPesqCliente in 'untPesqCliente.pas' {frmPesqCliente},
  untCadRotas in 'untCadRotas.pas' {frmCadRotas},
  untPesqProdutoItens in 'untPesqProdutoItens.pas' {frmPesqProdutoItens},
  untRomaneio in 'untRomaneio.pas' {frmRomaneio},
  untCadMotoristas in 'untCadMotoristas.pas' {frmCadMotoristas},
  untCadVeiculos in 'untCadVeiculos.pas' {frmCadVeiculos},
  untPesqPedido in 'untPesqPedido.pas' {frmPesqPedido},
  untCadPortador in 'untCadPortador.pas' {frmCadPortador},
  untLancDadosBasicCheque in 'untLancDadosBasicCheque.pas' {frmLancDadosBasicCheque},
  untPesqBanco in 'untPesqBanco.pas' {frmPesqBanco},
  untVendaFinalizacao in 'untVendaFinalizacao.pas' {frmVendaFinalizacao},
  untCntReceber in 'untCntReceber.pas' {frmCntReceber},
  untCntPagar in 'untCntPagar.pas' {frmCntPagar},
  untPesqVendedor in 'untPesqVendedor.pas' {frmPesqVendedor},
  untPesqRota in 'untPesqRota.pas' {frmPesqRota},
  untGraficoPedidos in 'untGraficoPedidos.pas' {frmGraficoPedidos},
  untProducao in 'untProducao.pas' {frmProducao},
  untConfiguracao in 'untConfiguracao.pas' {frmConfig},
  untCheque in 'untCheque.pas' {frmCheque},
  untRetornoItensPedido in 'untRetornoItensPedido.pas' {frmRetornoItensPedido},
  untPesqStatusDoc in 'untPesqStatusDoc.pas' {frmPesqStatusDoc},
  untEstoque in 'untEstoque.pas' {frmEstoque},
  untCadFiliais in 'untCadFiliais.pas' {frmCadFiliais},
  untWebMapa in 'untWebMapa.pas' {frmWebMapa},
  untMovInt in 'untMovInt.pas' {frmMovInt},
  untVendas in 'untVendas.pas' {frmVendas},
  untPesqProdutos in 'untPesqProdutos.pas' {frmPesqProdutos},
  untPesqEntregar in 'untPesqEntregar.pas' {frmPesqEntregar},
  untEmissaoBoleto in 'untEmissaoBoleto.pas' {frmEmissaoBoleto},
  untImpEtiquetasClientes in 'untImpEtiquetasClientes.pas' {frmImpEtiquetasClientes},
  untMovimentacaoCaixa in 'untMovimentacaoCaixa.pas' {frmMovCaixa},
  untBackUp in 'untBackUp.pas' {frmBackUp},
  untCompras in 'untCompras.pas' {frmCompras},
  untCompraFinalizacao in 'untCompraFinalizacao.pas' {frmCompraFinalizacao},
  untCadFuncionarios in 'untCadFuncionarios.pas' {frmCadFuncionarios},
  untPesqFuncionario in 'untPesqFuncionario.pas' {frmPesqFuncionario},
  untRegistro in 'untRegistro.pas' {frmRegistro},
  untControleMesas in 'untControleMesas.pas' {frmControleMesas},
  untRecebimentoDetalhe in 'untRecebimentoDetalhe.pas' {frmRecebimentoDetalhe},
  uRegistro in 'uRegistro.pas',
  untGrupoRelacion in 'untGrupoRelacion.pas' {frmGrupoRelacion},
  untSelectGrupos in 'untSelectGrupos.pas' {frmSelectGrupos},
  untOrdemServico in 'untOrdemServico.pas' {frmOrdemServico},
  untEmail in 'untEmail.pas' {frmEmail},
  untOutrosPagamentos in 'untOutrosPagamentos.pas' {frmOutrosPagamentos},
  untPesqCor in 'untPesqCor.pas' {frmPesqCor},
  untPesqTamanho in 'untPesqTamanho.pas' {frmPesqTamanho},
  uUtils in 'uUtils.pas',
  untEtiquetaPrateleira in 'untEtiquetaPrateleira.pas' {frmEtiquetaPrateleira},
  untConfigTabPreco in 'untConfigTabPreco.pas' {frmConfigTabPreco},
  untConfigTabPrecoGeral in 'untConfigTabPrecoGeral.pas' {frmConfigTabPrecGeral},
  uVerificaPermicao in 'uVerificaPermicao.pas',
  uContador in 'uContador.pas',
  untSelTabPreco in 'untSelTabPreco.pas' {frmSelTabPreco},
  untPreVenda in 'untPreVenda.pas' {frmPreVenda},
  untNumPreVenda in 'untNumPreVenda.pas' {frmNumPreVenda},
  untComissaoVendedor in 'untComissaoVendedor.pas' {frmComissaoVendedor},
  untGerarComissao in 'untGerarComissao.pas' {frmGerarComissao},
  untPrecItemAtualizacao in 'untPrecItemAtualizacao.pas' {frmPrecItemAtualizacao},
  untLocalizaItem in 'untLocalizaItem.pas' {frmLocalizaItem},
  untIncluirGastos in 'untIncluirGastos.pas' {frmIncluirGastos},
  untPagIncReceber in 'untPagIncReceber.pas' {frmPagIncReceber},
  untPagIncPagar in 'untPagIncPagar.pas' {frmPagIncPagar},
  untFluxoCaixa in 'untFluxoCaixa.pas' {frmFluxoCaixa},
  untGeraProdItens in 'untGeraProdItens.pas' {frmGeraProdItens},
  untBalanco in 'untBalanco.pas' {frmBalanco},
  uBaixaDocAutoReceber in 'uBaixaDocAutoReceber.pas',
  uContador2 in 'uContador2.pas',
  untDataThread in 'untDataThread.pas' {DMThread: TDataModule},
  untPularEtiquetas in 'untPularEtiquetas.pas' {frmPularEtiquetas},
  untCFOP in 'untCFOP.pas' {frmCFOP},
  untStatusNFe in 'untStatusNFe.pas' {frmStatusNFe},
  untRomaneioCntReceber in 'untRomaneioCntReceber.pas' {frmRomaneioCntReceber},
  untPesqCntReceber in 'untPesqCntReceber.pas' {frmPesqCntReceber},
  untPesqVendas in 'untPesqVendas.pas' {frmPesqVendas},
  untPlanoContas in 'untPlanoContas.pas' {frmPlanoContas},
  untNtDevolucaoInfo in 'untNtDevolucaoInfo.pas' {frmNtDevolucaoInfo},
  untCadTransportadora in 'untCadTransportadora.pas' {frmCadTransportadora},
  untPesqTransportadora in 'untPesqTransportadora.pas' {frmPesqTransportadora},
  untPesqVeiculo in 'untPesqVeiculo.pas' {frmPesqVeiculo},
  untTransportadoraDados in 'untTransportadoraDados.pas' {frmTransportadoraDados},
  untInutilizarNFe in 'untInutilizarNFe.pas' {frmInutilizarNFe},
  untNfe in 'untNfe.pas' {frmNfe},
  untPesqVendasPedidos in 'untPesqVendasPedidos.pas' {frmPesqVendasPedidos},
  untInfoAdicionalProduto in 'untInfoAdicionalProduto.pas' {frmInfoAdicionalProduto},
  untSelGrupo in 'untSelGrupo.pas' {frmSelGrupo},
  untItensXMLCompra in 'untItensXMLCompra.pas' {frmItensXMLCompra},
  untNFeCartaCorrecao in 'untNFeCartaCorrecao.pas' {frmNFeCartaCorrecao},
  untTipoCartaoCredito in 'untTipoCartaoCredito.pas' {frmTipoCartaoCredito},
  untPesqClienteCodigo in 'untPesqClienteCodigo.pas' {frmPesqClienteCodigo},
  untNFeInformacoesAdicionais in 'untNFeInformacoesAdicionais.pas' {frmNFeInformacoesAdicionais},
  UntCadNatOperacoes in 'UntCadNatOperacoes.pas' {frmCadNatOperacoes},
  untExportarProdBalanca in 'untExportarProdBalanca.pas' {frmExportarProdBalanca},
  untPedidoOuOrcamento in 'untPedidoOuOrcamento.pas' {frmPedidoOuOrcamento},
  untTroco in 'untTroco.pas' {frmTroco},
  untEntregaDados in 'untEntregaDados.pas' {frmEntregaDados},
  untMDFe in 'untMDFe.pas' {frmMDFe},
  untPesqNFe in 'untPesqNFe.pas' {frmPesqNFe},
  untPesqVeiculoMDFe in 'untPesqVeiculoMDFe.pas' {frmPesqVeiculoMDFe},
  untPesqMotoristaMDFe in 'untPesqMotoristaMDFe.pas' {frmPesqMotoristaMDFe},
  untpesqReboqueMDFe in 'untpesqReboqueMDFe.pas' {frmPesqReboqueMDFe},
  untMsgUsuarioNaoPermitido in 'untMsgUsuarioNaoPermitido.pas' {frmMenssagens},
  untConfigSistema in 'untConfigSistema.pas' {frmConfigSistema},
  untCadCaixa in 'untCadCaixa.pas' {frmCadCaixa},
  untPesqCST in 'untPesqCST.pas' {frmPesqCST},
  untPesqNFeNFCe in 'untPesqNFeNFCe.pas' {frmPesqNFeNFCe},
  untPesqIBPT in 'untPesqIBPT.pas' {frmPesqIBPT},
  untControleCheque in 'untControleCheque.pas' {frmControleCheque},
  untControleCartao in 'untControleCartao.pas' {frmControleCartao},
  Api in 'Api.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'SGP';
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TDMThread, DMThread);
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.Run;

end.
