INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (1, '01', 'Operação Tributável com Alíquota Básica');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (2, '02', 'Operação Tributável com Alíquota Diferenciada');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (3, '03', 'Operação Tributável com Alíquota por Unidade de Medida de Produto');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (4, '04', 'Operação Tributável Monofásica - Revenda a Alíquota Zero');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (5, '05', 'Operação Tributável por Substituição Tributária');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (6, '06', 'Operação Tributável a Alíquota Zero');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (7, '07', 'Operação Isenta da Contribuição');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (8, '08', 'Operação sem Incidência da Contribuição');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (9, '09', 'Operação com Suspensão da Contribuição');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (10, '49', 'Outras Operações de Saída');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (11, '50', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (12, '51', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (13, '52', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (14, '53', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (15, '54', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (16, '55', 'Operação com Direito a Crédito - Vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (17, '56', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (18, '60', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (19, '61', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (20, '62', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (21, '63', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (22, '64', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (23, '65', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (24, '66', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (25, '67', 'Crédito Presumido - Outras Operações');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (29, '70', 'Operação de Aquisição sem Direito a Crédito');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (30, '71', 'Operação de Aquisição com Isenção');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (31, '72', 'Operação de Aquisição com Suspensão');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (32, '73', 'Operação de Aquisição a Alíquota Zero');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (33, '74', 'Operação de Aquisição sem Incidência da Contribuição');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (34, '75', 'Operação de Aquisição por Substituição Tributária');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (35, '98', 'Outras Operações de Entrada');
INSERT INTO CST_PIS_COFINS (ID, CST, DESCRICAO) VALUES (36, '99', 'Outras Operações');

COMMIT WORK;
